### ISSUE TITLE
on unhandled_stream | proxy stream to remote server 

### ISSUE THREAD

**Issue by fas3r** [davedoesdev/browser-http2-duplex#1]
Hello, 

on unhandled_stream, would it be possible to restream/proxy the request to a backend server also running http2 ?

for example, a request https://x.z.com/profil hit server A, it does not find on the local server. 
On "unhandled_stream", it proxy/stream the request to an backend server HTTP2 call "profil".

Thanks.

**Comment by davedoesdev** [comment]
@fas3r yes, you should be able to do that
