### ISSUE TITLE
Failure on Chrome 85 with `#enable-experimental-web-platform-features` enabled

### ISSUE THREAD

**Issue by radu-matei** [davedoesdev/browser-http2-duplex#5]
First of all, thanks for the effort put into this library!

Trying out various environments, I found out that Chrome 85 with the experimental features enabled will result in writes to the duplex remaining in `pending`, and any disconnection event results in error closing the stream:

```
>> events.js:291
>>       throw er; // Unhandled 'error' event
>>       ^
>>
>> Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
>>     at ServerHttp2Stream._destroy (internal/http2/core.js:2124:13)
>>     at ServerHttp2Stream.destroy (internal/streams/destroy.js:36:8)
>>     at Http2Stream.onStreamClose (internal/http2/core.js:508:12)
>> Emitted 'error' event on ServerHttp2Stream instance at:
>>     at emitErrorNT (internal/streams/destroy.js:100:8)
>>     at emitErrorCloseNT (internal/streams/destroy.js:68:3)
>>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>>   code: 'ERR_HTTP2_STREAM_ERROR'
>> }
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
```

**Comment by davedoesdev** [comment]
Hey @radu-matei thanks for the bug report, appreciate it.
Coincidentally I've just started looking at this. Now nwjs has updated to Chrome 85 the tests are failing when I enable the flag. I'll see what's up.
Thanks again!

**Comment by davedoesdev** [comment]
I've made some changes on master which fix the example. The tests aren't passing because I think I need nwjs to use 14.9.0 in order to pick up https://github.com/nodejs/node/commit/0e30c5bc261756dffaa874e4a9ef9858f16ba1d9

**Comment by davedoesdev** [comment]
@radu-matei this should now be fixed in version 5.0.0

**Comment by radu-matei** [comment]
Thanks for tackling this!

Writing on the stream now works, but closing the tab still results in the same error as above.

**Comment by davedoesdev** [comment]
Sigh, I'm sure I tested and fixed that. Perhaps I messed it up. I'll take a look in a couple of days, hope that's okay.

**Comment by davedoesdev** [comment]
@radu-matei OK this _should_ be fixed in version 5.0.1 :smile:

**Comment by davedoesdev** [comment]
@radu-matei Version 5.3.0 has overhaulled destroy behaviour. If you could test it that would be great.

**Comment by davedoesdev** [comment]
@radu-matei version 5.3.1 published with updated dependencies. Is this issue fixed now?

**Comment by radu-matei** [comment]
Hey, @davedoesdev, so sorry I missed the previous comment.
I just tested again with the latest version and everything seems to work, thanks a lot!
